site_name: NanoLab - FCFM
site_url: https://mydomain.org/mysite

theme:
  name: material
  custom_dir: overrides
  logo: "images/logo/logo.png"
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: orange
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - navigation.instant    
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top

plugins:
  - search
  - blog

nav:
  - Home: index.md
  - News:
    - blog/index.md
  - Publications: publications.md
  - People: people.md
  - Documentation:
    - documentation/index.md
    - Software:
        - Laser Setup: documentation/software/laser_setup_repo/README.md
    - Hardware:
        - Clicker: documentation/hardware/clicker_repo/README.md
        - Temperature Sensor v1: documentation/hardware/temp_sensor_v1_repo/README.md
 
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra_css:
  - assets/custom.css

use_directory_urls: false
