site_name: NanoLab - FCFM
site_url: https://mydomain.org/mysite

theme:
  name: material
  custom_dir: overrides
  logo: "images/logo/logo.png"
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: orange
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - navigation.instant    
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top

plugins:
  - search
  - blog

nav:
  - Home: index.md
  - About: about/about.md
  - People: people.md
  - Publications: publications.md
  - Documentation:
      - Software:
          - Laser Setup: software/laser_setup_repo/README.md
      - Hardware:
          - Clicker: hardware/clicker_repo/README.md
          - Temperature Sensor v1: hardware/temp_sensor_v1_repo/README.md
  - News:
    - blog/index.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/custom.css

use_directory_urls: false
